/* eslint-disable */

/**
 * Generated by Verge3D Puzzles v.4.8.0
 * Thu, 13 Nov 2025 19:18:42 GMT
 * Prefer not editing this file as your changes may get overridden once Puzzles are saved.
 * Check out https://www.soft8soft.com/docs/manual/en/introduction/Using-JavaScript.html
 * for the information on how to add your own JavaScript to Verge3D apps.
 */
function createPL(v3d = window.v3d) {

// global variables used in the init tab
const _initGlob = {
    percentage: 0,
    output: {
        initOptions: {
            fadeAnnotations: true,
            useBkgTransp: false,
            preserveDrawBuf: false,
            useCompAssets: false,
            useFullscreen: true,
            useCustomPreloader: false,
            preloaderStartCb: function() {},
            preloaderProgressCb: function() {},
            preloaderEndCb: function() {},
        },
    },
};


// global variables/constants used by puzzles' functions
var _pGlob = {};

_pGlob.objCache = {};
_pGlob.fadeAnnotations = true;
_pGlob.pickedObject = '';
_pGlob.hoveredObject = '';
_pGlob.mediaElements = {};
_pGlob.loadedFile = '';
_pGlob.states = [];
_pGlob.percentage = 0;
_pGlob.openedFile = '';
_pGlob.openedFileMeta = {};
_pGlob.xrSessionAcquired = false;
_pGlob.xrSessionCallbacks = [];
_pGlob.screenCoords = new v3d.Vector2();
_pGlob.intervalTimers = {};
_pGlob.customEvents = new v3d.EventDispatcher();
_pGlob.eventListeners = [];
_pGlob.htmlElements = new Set();
_pGlob.materialsCache = new Map();

_pGlob.AXIS_X = new v3d.Vector3(1, 0, 0);
_pGlob.AXIS_Y = new v3d.Vector3(0, 1, 0);
_pGlob.AXIS_Z = new v3d.Vector3(0, 0, 1);
_pGlob.MIN_DRAG_SCALE = 10e-4;
_pGlob.SET_OBJ_ROT_EPS = 1e-8;

_pGlob.vec2Tmp = new v3d.Vector2();
_pGlob.vec2Tmp2 = new v3d.Vector2();
_pGlob.vec3Tmp = new v3d.Vector3();
_pGlob.vec3Tmp2 = new v3d.Vector3();
_pGlob.vec3Tmp3 = new v3d.Vector3();
_pGlob.vec3Tmp4 = new v3d.Vector3();
_pGlob.eulerTmp = new v3d.Euler();
_pGlob.eulerTmp2 = new v3d.Euler();
_pGlob.quatTmp = new v3d.Quaternion();
_pGlob.quatTmp2 = new v3d.Quaternion();
_pGlob.colorTmp = new v3d.Color();
_pGlob.mat4Tmp = new v3d.Matrix4();
_pGlob.planeTmp = new v3d.Plane();
_pGlob.raycasterTmp = new v3d.Raycaster(); // always check visibility

const createPzLib = ({ v3d=null, appInstance=null }) => {
    function isObjectWorthProcessing(obj) {
        return obj.type !== 'AmbientLight' && obj.name !== '' &&
                !(obj.isMesh && obj.isMaterialGeneratedMesh) &&
                !obj.isAuxClippingMesh;
    }
        
    function getObjectByName(objName) {
        let objFound = null;
    
        const pGlobAvailable = _pGlob !== undefined;
        if (pGlobAvailable && objName in _pGlob.objCache) {
            objFound = _pGlob.objCache[objName] || null;
        }
    
        if (objFound && objFound.name === objName) {
            return objFound;
        }
    
        if (appInstance.scene) {
            appInstance.scene.traverse(obj => {
                if (!objFound && isObjectWorthProcessing(obj) && (obj.name === objName)) {
                    objFound = obj;
                    if (pGlobAvailable) {
                        _pGlob.objCache[objName] = objFound;
                    }
                }
            });
        }
        return objFound;
    }
        
    function getObjectNamesByGroupName(groupName) {
        const objNameList = [];
        appInstance.scene.traverse(obj => {
            if (isObjectWorthProcessing(obj)) {
                const objGroupNames = obj.groupNames;
                if (!objGroupNames) {
                    return;
                }
    
                for (let i = 0; i < objGroupNames.length; i++) {
                    const objGroupName = objGroupNames[i];
                    if (objGroupName === groupName) {
                        objNameList.push(obj.name);
                    }
                }
            }
        });
        return objNameList;
    }
        
    function getAllObjectNames() {
        const objNameList = [];
        appInstance.scene.traverse(obj => {
            if (isObjectWorthProcessing(obj)) {
                objNameList.push(obj.name);
            }
        });
        return objNameList;
    }
        
    function retrieveObjectNamesAccum(currObjNames, namesAccum) {
        if (typeof currObjNames === 'string') {
            namesAccum.push(currObjNames);
        } else if (Array.isArray(currObjNames) && currObjNames[0] === 'GROUP') {
            const newObjNames = getObjectNamesByGroupName(currObjNames[1]);
            for (let i = 0; i < newObjNames.length; i++) {
                namesAccum.push(newObjNames[i]);
            }
        } else if (Array.isArray(currObjNames) && currObjNames[0] === 'ALL_OBJECTS') {
            const newObjNames = getAllObjectNames();
            for (let i = 0; i < newObjNames.length; i++) {
                namesAccum.push(newObjNames[i]);
            }
        } else if (Array.isArray(currObjNames)) {
            for (let i = 0; i < currObjNames.length; i++) {
                retrieveObjectNamesAccum(currObjNames[i], namesAccum);
            }
        }
    }
        
    function retrieveObjectNames(objNames) {
        const accum = [];
        retrieveObjectNamesAccum(objNames, accum);
        return accum.filter(name => name !== '');
    }
        
    function areListenersSame(target0, type0, listener0, optionsOrUseCapture0,
            target1, type1, listener1, optionsOrUseCapture1) {
        const capture0 = Boolean(optionsOrUseCapture0 instanceof Object
                ? optionsOrUseCapture0.capture : optionsOrUseCapture0);
        const capture1 = Boolean(optionsOrUseCapture1 instanceof Object
                ? optionsOrUseCapture1.capture : optionsOrUseCapture1);
        return target0 === target1 && type0 === type1 && listener0 === listener1
                && capture0 === capture1;
    }
        
    function bindListener(target, type, listener, optionsOrUseCapture) {
        const alreadyExists = _pGlob.eventListeners.some(elem => {
            return areListenersSame(elem.target, elem.type, elem.listener,
                    elem.optionsOrUseCapture, target, type, listener,
                    optionsOrUseCapture);
        });
    
        if (!alreadyExists) {
            target.addEventListener(type, listener, optionsOrUseCapture);
            _pGlob.eventListeners.push({ target, type, listener,
                    optionsOrUseCapture });
        }
    }
        
    function getSceneAnimFrameRate(scene) {
        if (scene && 'animFrameRate' in scene.userData) {
            return scene.userData.animFrameRate;
        }
        return 24;
    }
        
    function getSceneByAction(action) {
        const root = action.getRoot();
        let scene = root.type === 'Scene' ? root : null;
        root.traverseAncestors(ancObj => {
            if (ancObj.type === 'Scene') {
                scene = ancObj;
            }
        });
        return scene;
    }
        
    function transformCoordsSpace(coords, spaceFrom, spaceTo, noSignChange=false) {
    
        if (spaceFrom === spaceTo) {
            return coords;
        }
    
        const y = coords.y;
        const z = coords.z;
    
        if (spaceFrom === 'Z_UP_RIGHT' && spaceTo === 'Y_UP_RIGHT') {
            coords.y = z;
            coords.z = noSignChange ? y : -y;
        } else if (spaceFrom === 'Y_UP_RIGHT' && spaceTo === 'Z_UP_RIGHT') {
            coords.y = noSignChange ? z : -z;
            coords.z = y;
        } else {
            console.error('transformCoordsSpace: Unsupported coordinate space');
        }
    
        return coords;
    }
        
    function getSceneCoordSystem() {
        const scene = appInstance.scene;
        if (scene && 'coordSystem' in scene.userData) {
            return scene.userData.coordSystem;
        }
    
        return 'Y_UP_RIGHT';
    }
        
    function generateUniqueName(name, isUniqueCb) {
        let uniqueName = name;
    
        if (isUniqueCb !== undefined) {
            while (!isUniqueCb(uniqueName)) {
                const r = uniqueName.match(/^(.*?)(\d+)$/);
                if (!r) {
                    uniqueName += '2';
                } else {
                    uniqueName = r[1] + (Number.parseInt(r[2], 10) + 1);
                }
            }
        }
    
        return uniqueName;
    }
        
    function generateUniqueObjectName(name) {
        return generateUniqueName(name, name => !Boolean(getObjectByName(name)));
    }

    return {
        getObjectByName, retrieveObjectNames, bindListener, getSceneAnimFrameRate,
        getSceneByAction, transformCoordsSpace, getSceneCoordSystem, generateUniqueObjectName,
    };
};

var PL = {};



// backward compatibility
if (v3d[Symbol.toStringTag] !== 'Module') {
    v3d.PL = v3d.puzzles = PL;
}

PL.procedures = PL.procedures || {};




PL.execInitPuzzles = function(options) {
    // always null, should not be available in "init" puzzles
    var appInstance = null;
    // app is more conventional than appInstance (used in exec script and app templates)
    var app = null;

    const PzLib = createPzLib({ v3d });

    // provide the container's id to puzzles that need access to the container
    _initGlob.container = options !== undefined && 'container' in options
            ? options.container : "";

    

    // initSettings puzzle
_initGlob.output.initOptions.fadeAnnotations = true;
_initGlob.output.initOptions.useBkgTransp = false;
_initGlob.output.initOptions.preserveDrawBuf = false;
_initGlob.output.initOptions.useCompAssets = false;
_initGlob.output.initOptions.useFullscreen = true;

    return _initGlob.output;
}

PL.init = function(appInstance, initOptions) {

// app is more conventional than appInstance (used in exec script and app templates)
var app = appInstance;

const PzLib = createPzLib({ v3d, appInstance });

initOptions = initOptions || {};

if ('fadeAnnotations' in initOptions) {
    _pGlob.fadeAnnotations = initOptions.fadeAnnotations;
}

this.procedures["HideAll"] = HideAll;
this.procedures["posGeneral"] = posGeneral;
this.procedures["ModoP1"] = ModoP1;
this.procedures["ModoP1off"] = ModoP1off;
this.procedures["VistaLibre"] = VistaLibre;
this.procedures["VistaLibreOff"] = VistaLibreOff;
this.procedures["inicio"] = inicio;
this.procedures["Cambio"] = Cambio;
this.procedures["zoneA"] = zoneA;
this.procedures["disable"] = disable;
this.procedures["VA"] = VA;
this.procedures["zoneC"] = zoneC;
this.procedures["VB"] = VB;
this.procedures["VC"] = VC;
this.procedures["VC5"] = VC5;
this.procedures["vA1"] = vA1;
this.procedures["vA2"] = vA2;
this.procedures["vA3"] = vA3;
this.procedures["vA4"] = vA4;
this.procedures["vA5"] = vA5;
this.procedures["vA6"] = vA6;
this.procedures["vB1"] = vB1;
this.procedures["vB2"] = vB2;
this.procedures["vB3"] = vB3;
this.procedures["vB4"] = vB4;
this.procedures["vB5"] = vB5;
this.procedures["vB6"] = vB6;
this.procedures["vB7"] = vB7;
this.procedures["vB8"] = vB8;
this.procedures["vBx"] = vBx;
this.procedures["vC1"] = vC1;
this.procedures["vC2"] = vC2;
this.procedures["vC3"] = vC3;
this.procedures["vC4"] = vC4;
this.procedures["vCx"] = vCx;
this.procedures["vD1"] = vD1;
this.procedures["quitarAlarmas"] = quitarAlarmas;
this.procedures["vD2"] = vD2;

var PROC = {
    "HideAll": HideAll,
    "posGeneral": posGeneral,
    "ModoP1": ModoP1,
    "ModoP1off": ModoP1off,
    "VistaLibre": VistaLibre,
    "VistaLibreOff": VistaLibreOff,
    "inicio": inicio,
    "Cambio": Cambio,
    "zoneA": zoneA,
    "disable": disable,
    "VA": VA,
    "zoneC": zoneC,
    "VB": VB,
    "VC": VC,
    "VC5": VC5,
    "vA1": vA1,
    "vA2": vA2,
    "vA3": vA3,
    "vA4": vA4,
    "vA5": vA5,
    "vA6": vA6,
    "vB1": vB1,
    "vB2": vB2,
    "vB3": vB3,
    "vB4": vB4,
    "vB5": vB5,
    "vB6": vB6,
    "vB7": vB7,
    "vB8": vB8,
    "vBx": vBx,
    "vC1": vC1,
    "vC2": vC2,
    "vC3": vC3,
    "vC4": vC4,
    "vCx": vCx,
    "vD1": vD1,
    "quitarAlarmas": quitarAlarmas,
    "vD2": vD2,
};

var VARS = Object.defineProperties({}, {
    'hideObj': { get: function() { return hideObj; }, set: function(val) { hideObj = val; } },
    'A7una': { get: function() { return A7una; }, set: function(val) { A7una = val; } },
    'VB6 obj': { get: function() { return VB6_obj; }, set: function(val) { VB6_obj = val; } },
});

var hideObj, A7una, VB6_obj;

// zoomCamera puzzle
function zoomCamera(objSelector, duration, doSlot) {

    duration = Math.max(0, duration);

    const objNames = PzLib.retrieveObjectNames(objSelector);

    const zoomObjects = [];
    objNames.forEach(function(name) {
        const obj = PzLib.getObjectByName(name);
        if (obj) {
            zoomObjects.push(obj);
        }
    });

    if (!zoomObjects.length) {
        return;
    }

    const camera = appInstance.getCamera();

    const zoom = [camera.zoom]; // for orthographic camera only

    const pos = _pGlob.vec3Tmp, target = _pGlob.vec3Tmp2;
    v3d.CameraUtils.calcCameraZoomToObjectsParams(camera, zoomObjects,
            pos, target, zoom);

    if (appInstance.controls && appInstance.controls.tween) {
        // orbit and flying cameras
        if (!appInstance.controls.inTween) {
            if (camera.isOrthographicCamera) {
                appInstance.controls.tweenZoomTo(target, zoom[0],
                        duration, doSlot);
            } else {
                appInstance.controls.tween(pos, target, duration, doSlot);
            }
        }
    } else {
        // TODO: static camera, just position it for now
        if (camera.parent) {
            camera.parent.worldToLocal(pos);
        }
        camera.position.copy(pos);
        camera.lookAt(target);
        camera.zoom = zoom[0];
        camera.updateProjectionMatrix();
        doSlot();
    }
}

// show and hide puzzles
function changeVis(objSelector, bool) {
    var objNames = PzLib.retrieveObjectNames(objSelector);

    for (var i = 0; i < objNames.length; i++) {
        var objName = objNames[i]
        if (!objName)
            continue;
        var obj = PzLib.getObjectByName(objName);
        if (!obj)
            continue;
        obj.visible = bool;
        obj.resolveMultiMaterial().forEach(function(objR) {
            objR.visible = bool;
        });
    }
}

_pGlob.animMixerCallbacks = [];

var initAnimationMixer = function() {

    function onMixerFinished(e) {
        var cb = _pGlob.animMixerCallbacks;
        var found = [];
        for (var i = 0; i < cb.length; i++) {
            if (cb[i][0] == e.action) {
                cb[i][0] = null; // desactivate
                found.push(cb[i][1]);
            }
        }
        for (var i = 0; i < found.length; i++) {
            found[i]();
        }
    }

    return function initAnimationMixer() {
        if (appInstance.mixer && !appInstance.mixer.hasEventListener('finished', onMixerFinished)) {
            PzLib.bindListener(appInstance.mixer, 'finished', onMixerFinished);
        }
    };

}();

// animation puzzles
function operateAnimation(operation, animations, from, to, loop, speed, callback, rev) {
    if (!animations)
        return;
    // input can be either single obj or array of objects
    if (typeof animations == "string")
        animations = [animations];

    function processAnimation(animName) {
        var action = v3d.SceneUtils.getAnimationActionByName(appInstance, animName);
        if (!action)
            return;
        switch (operation) {
        case 'PLAY':
            if (!action.isRunning()) {
                action.reset();
                if (loop && (loop != "AUTO"))
                    action.loop = v3d[loop];
                var scene = PzLib.getSceneByAction(action);
                var frameRate = PzLib.getSceneAnimFrameRate(scene);

                action.repetitions = Infinity;

                var timeScale = Math.abs(parseFloat(speed));
                if (rev)
                    timeScale *= -1;

                action.timeScale = timeScale;
                action.timeStart = from !== null ? from/frameRate : 0;
                if (to !== null) {
                    action.getClip().duration = to/frameRate;
                } else {
                    action.getClip().resetDuration();
                }
                action.time = timeScale >= 0 ? action.timeStart : action.getClip().duration;

                action.paused = false;
                action.play();

                // push unique callbacks only
                var callbacks = _pGlob.animMixerCallbacks;
                var found = false;

                for (var j = 0; j < callbacks.length; j++)
                    if (callbacks[j][0] == action && callbacks[j][1] == callback)
                        found = true;

                if (!found)
                    _pGlob.animMixerCallbacks.push([action, callback]);
            }
            break;
        case 'STOP':
            action.stop();

            // remove callbacks
            var callbacks = _pGlob.animMixerCallbacks;
            for (var j = 0; j < callbacks.length; j++)
                if (callbacks[j][0] == action) {
                    callbacks.splice(j, 1);
                    j--
                }

            break;
        case 'PAUSE':
            action.paused = true;
            break;
        case 'RESUME':
            action.paused = false;
            break;
        case 'SET_FRAME':
            var scene = PzLib.getSceneByAction(action);
            var frameRate = PzLib.getSceneAnimFrameRate(scene);
            action.time = from ? from/frameRate : 0;
            action.play();
            action.paused = true;
            break;
        case 'SET_SPEED':
            var timeScale = parseFloat(speed);
            action.timeScale = rev ? -timeScale : timeScale;
            break;
        }
    }

    for (var i = 0; i < animations.length; i++) {
        var animName = animations[i];
        if (animName)
            processAnimation(animName);
    }

    initAnimationMixer();
}

// setCameraParam puzzle
function setCameraParam(type, camSelector, param) {

    const camNames = PzLib.retrieveObjectNames(camSelector);

    camNames.forEach(function(camName) {
        if (!camName)
            return;

        var cam = PzLib.getObjectByName(camName);
        if (!cam || !cam.isCamera) return;

        if (!(cam.isPerspectiveCamera || cam.isOrthographicCamera)) {
            console.error('setCameraParam: Incompatible camera type, have to be perspective or orthographic');
            return;
        }

        let isSetOrbitParam = false;
        let isSetFirstpersonParam = false;

        switch (type) {
            case 'ORBIT_MIN_DISTANCE_PERSP':
            case 'ORBIT_MAX_DISTANCE_PERSP':
            case 'ORBIT_MIN_ZOOM_ORTHO':
            case 'ORBIT_MAX_ZOOM_ORTHO':
            case 'ORBIT_MIN_VERTICAL_ANGLE':
            case 'ORBIT_MAX_VERTICAL_ANGLE':
            case 'ORBIT_MIN_HORIZONTAL_ANGLE':
            case 'ORBIT_MAX_HORIZONTAL_ANGLE':
            case 'ORBIT_ALLOW_TURNOVER':
                isSetOrbitParam = true;
                break;
            case 'ENABLE_COLLISIONS':
                isSetFirstpersonParam = true;
                break;
        }

        let isSetControlsParam = (['ROTATION_SPEED', 'MOVEMENT_SPEED', 'ALLOW_PANNING', 'ALLOW_ZOOM', 'ALLOW_CTRL_ZOOM', 'KEYBOARD_CONTROLS'].includes(type) || isSetOrbitParam || isSetFirstpersonParam);

        if (isSetControlsParam) {
            if (!cam.controlSettings) {
                console.error('setCameraParam: The "' + camName +'" camera has no control settings assigned');
                return;
            } else if ((isSetOrbitParam && cam.controlSettings.type != 'ORBIT') ||
                    (isSetFirstpersonParam && cam.controlSettings.type != 'FIRST_PERSON')) {
                console.error('setCameraParam: Incompatible camera controls: ' + cam.controlSettings.type);
                return;
            }
        }

        switch (type) {
            case 'FIELD_OF_VIEW':
                if (cam.isPerspectiveCamera) {
                    cam.fov = param;
                    cam.updateProjectionMatrix();
                } else {
                    console.error('setCameraParam: Incompatible camera type, have to be perspective');
                    return;
                }
                break;
            case 'ORTHO_SCALE':
                if (cam.isOrthographicCamera) {
                    cam.zoom = param;
                    cam.updateProjectionMatrix();
                } else {
                    console.error('setCameraParam: Incompatible camera type, have to be orthographic');
                    return;
                }
                break;
            case 'ROTATION_SPEED':
                cam.controlSettings.rotateSpeed = param;
                break;
            case 'MOVEMENT_SPEED':
                cam.controlSettings.moveSpeed = param;
                break;
            case 'ALLOW_PANNING':
                cam.controlSettings.enablePan = param;
                break;
            case 'ALLOW_ZOOM':
                cam.controlSettings.enableZoom = param;
                break;
            case 'ALLOW_CTRL_ZOOM':
                cam.controlSettings.enableCtrlZoom = param;
                break;
            case 'KEYBOARD_CONTROLS':
                cam.controlSettings.enableKeys = param;
                break;
            case 'ORBIT_MIN_DISTANCE_PERSP':
                if (cam.isPerspectiveCamera) {
                    cam.controlSettings.orbitMinDistance = param;
                } else {
                    console.error('setCameraParam: Incompatible camera type, have to be perspective');
                    return;
                }
                break;
            case 'ORBIT_MAX_DISTANCE_PERSP':
                if (cam.isPerspectiveCamera) {
                    cam.controlSettings.orbitMaxDistance = param;
                } else {
                    console.error('setCameraParam: Incompatible camera type, have to be perspective');
                    return;
                }
                break;
            case 'ORBIT_MIN_ZOOM_ORTHO':
                if (cam.isOrthographicCamera) {
                    cam.controlSettings.orbitMinZoom = param;
                } else {
                    console.error('setCameraParam: Incompatible camera type, have to be orthographic');
                    return;
                }
                break;
            case 'ORBIT_MAX_ZOOM_ORTHO':
                if (cam.isOrthographicCamera) {
                    cam.controlSettings.orbitMaxZoom = param;
                } else {
                    console.error('setCameraParam: Incompatible camera type, have to be orthographic');
                    return;
                }
                break;
            case 'ORBIT_MIN_VERTICAL_ANGLE':
                cam.controlSettings.orbitMinPolarAngle = v3d.MathUtils.degToRad(param);
                break;
            case 'ORBIT_MAX_VERTICAL_ANGLE':
                cam.controlSettings.orbitMaxPolarAngle = v3d.MathUtils.degToRad(param);
                break;
            case 'ORBIT_MIN_HORIZONTAL_ANGLE':
                cam.controlSettings.orbitMinAzimuthAngle = v3d.MathUtils.degToRad(param);
                break;
            case 'ORBIT_MAX_HORIZONTAL_ANGLE':
                cam.controlSettings.orbitMaxAzimuthAngle = v3d.MathUtils.degToRad(param);
                break;
            case 'ORBIT_ALLOW_TURNOVER':
                cam.controlSettings.orbitEnableTurnover = param;
                break;
            case 'ENABLE_COLLISIONS':
                cam.controlSettings.enableCollisions = param;
                break;
            case 'CLIP_START':
                cam.near = param;
                cam.updateProjectionMatrix();
                break;
            case 'CLIP_END':
                cam.far = param;
                cam.updateProjectionMatrix();
                break;
        }

        if (isSetControlsParam)
            appInstance.enableControls();

    });
}

// setTimeout puzzle
function registerSetTimeout(timeout, callback) {
    window.setTimeout(callback, 1000 * timeout);
}

// Describe this function...
function HideAll() {
  changeVis(hideObj, false);
}

// tweenCamera puzzle
function tweenCamera(posOrObj, targetOrObj, duration, doSlot, movementType) {
    var camera = appInstance.getCamera();

    if (Array.isArray(posOrObj)) {
        var worldPos = _pGlob.vec3Tmp.fromArray(posOrObj);
        worldPos = PzLib.transformCoordsSpace(worldPos,
                PzLib.getSceneCoordSystem(), 'Y_UP_RIGHT');
    } else if (posOrObj) {
        var posObj = PzLib.getObjectByName(posOrObj);
        if (!posObj) return;
        var worldPos = posObj.getWorldPosition(_pGlob.vec3Tmp);
    } else {
        // empty input means: don't change the position
        var worldPos = camera.getWorldPosition(_pGlob.vec3Tmp);
    }

    if (Array.isArray(targetOrObj)) {
        var worldTarget = _pGlob.vec3Tmp2.fromArray(targetOrObj);
        worldTarget = PzLib.transformCoordsSpace(worldTarget,
                PzLib.getSceneCoordSystem(), 'Y_UP_RIGHT');
    } else {
        var targObj = PzLib.getObjectByName(targetOrObj);
        if (!targObj) return;
        var worldTarget = targObj.getWorldPosition(_pGlob.vec3Tmp2);
    }

    duration = Math.max(0, duration);

    if (appInstance.controls && appInstance.controls.tween) {
        // orbit and flying cameras
        if (!appInstance.controls.inTween) {
            appInstance.controls.tween(worldPos, worldTarget, duration, doSlot,
                    movementType);
        }
    } else {
        // TODO: static camera, just position it for now
        if (camera.parent) {
            camera.parent.worldToLocal(worldPos);
        }
        camera.position.copy(worldPos);
        camera.lookAt(worldTarget);
        doSlot();
    }
}

// Describe this function...
function posGeneral() {
  tweenCamera('A', 'general', 0.8, function() {}, 1);
}

// Describe this function...
function ModoP1() {

  Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('' + '\n' +
  'if (window.LookOnlyControls) {window.LookOnlyControls.enable();}' + '\n' +
  '')))(appInstance, v3d, PL, VARS, PROC);

}

// Describe this function...
function ModoP1off() {

  Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('if (window.LookOnlyControls) {' + '\n' +
  '    window.LookOnlyControls.disable();' + '\n' +
  '}')))(appInstance, v3d, PL, VARS, PROC);

}

// Describe this function...
function VistaLibre() {

  Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('// CORRECCIÓN: Llama al método usando el objeto' + '\n' +
  'window.LookOnlyControls.TeclasOn();')))(appInstance, v3d, PL, VARS, PROC);

}

// Describe this function...
function VistaLibreOff() {

  Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('// CORRECCIÓN: Llama al método usando el objeto' + '\n' +
  'window.LookOnlyControls.TeclasOff();')))(appInstance, v3d, PL, VARS, PROC);

}

// Describe this function...
function inicio() {
}

// outline puzzle
function outline(objSelector, doWhat) {
    var objNames = PzLib.retrieveObjectNames(objSelector);

    if (!appInstance.postprocessing || !appInstance.postprocessing.outlinePass)
        return;
    var outlineArray = appInstance.postprocessing.outlinePass.selectedObjects;
    for (var i = 0; i < objNames.length; i++) {
        var objName = objNames[i];
        var obj = PzLib.getObjectByName(objName);
        if (!obj)
            continue;
        if (doWhat == "ENABLE") {
            if (outlineArray.indexOf(obj) == -1)
                outlineArray.push(obj);
        } else {
            var index = outlineArray.indexOf(obj);
            if (index > -1)
                outlineArray.splice(index, 1);
        }
    }
}

// Describe this function...
function Cambio() {
  outline(['ALL_OBJECTS'], 'DISABLE');
  ModoP1off();
  registerSetTimeout(0.1, function() {
    posGeneral();
    registerSetTimeout(1, function() {

      Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', 'detenerAlarma();')(appInstance, v3d, PL, VARS, PROC);

      HideAll();
    });
  });
}

// autoRotateCamera puzzle
function autoRotateCamera(enabled, speed) {

    if (appInstance.controls && appInstance.controls instanceof v3d.OrbitControls) {
        appInstance.controls.autoRotate = enabled;
        appInstance.controls.autoRotateSpeed = speed;
    } else {
        console.error('autorotate camera: Wrong controls type');
    }
}

// addAnnotation and removeAnnotation puzzles
function handleAnnot(add, annot, objSelector, contents, id, name) {
    var objNames = PzLib.retrieveObjectNames(objSelector);

    for (var i = 0; i < objNames.length; i++) {
        var objName = objNames[i];
        if (!objName)
            continue;
        var obj = PzLib.getObjectByName(objName);
        if (!obj)
            continue;
        // check if it already has an annotation and remove it
        for (var j = 0; j < obj.children.length; j++) {
            var child = obj.children[j];
            if (child.type == "Annotation") {
                // delete all childs of annotation
                child.traverse(function(child2) {
                    if (child2.isAnnotation)
                        child2.dispose();
                    });
                obj.remove(child);
            }
        }
        if (add) {
            var aObj = new v3d.Annotation(appInstance.container, annot, contents);
            aObj.name = PzLib.generateUniqueObjectName(name ? name : annot);
            aObj.fadeObscured = _pGlob.fadeAnnotations;
            if (id) {
                aObj.annotation.id = id;
                aObj.annotationDialog.id = id+'_dialog';
            }
            obj.add(aObj);
        }
    }
}

// Describe this function...
function zoneA() {
  autoRotateCamera(false, 3);
  handleAnnot(true, 'Planta Molibdeno', 'ZoneA', '', 'zoneA', undefined);
  tweenCamera('', 'ZoneA', 0.8, function() {}, 0);
  registerSetTimeout(1, function() {
    ModoP1();
    registerSetTimeout(1, function() {

      Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('import("../lists/v3d-button-lists.js");' + '\n' +
      'import("../js/Proceso/ProcesoA.js");')))(appInstance, v3d, PL, VARS, PROC);

    });
  });
}

// Describe this function...
function disable() {
  changeVis(['ALL_OBJECTS'], true);

  operateAnimation('STOP', 'Armature', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('STOP', 'Puerta1', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('STOP', 'Puerta2', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('STOP', 'Armature.001', null, null, 'AUTO', 1,
          function() {}, false);

      quitarAlarmas();
  ModoP1();
  outline(['ALL_OBJECTS'], 'DISABLE');
}

// Describe this function...
function VA() {
  Cambio();
}

// Describe this function...
function zoneC() {
  registerSetTimeout(1, function() {
    tweenCamera('', 'ZoneC', 0.8, function() {}, 0);
  });
}

// Describe this function...
function VB() {
  Cambio();
}

// Describe this function...
function VC() {
  Cambio();
  handleAnnot(true, 'Espesadores', 'ZoneC', '', 'zoneC', undefined);
  registerSetTimeout(1, function() {
    ModoP1();
  });
}

// Describe this function...
function VC5() {
  Cambio();

  Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('crearCardModulo(' + '\n' +
  '  "Puntos de Reunión - Evacuación",' + '\n' +
  '  "../img/C.png",' + '\n' +
  '  { duration: 2500 }' + '\n' +
  ');')))(appInstance, v3d, PL, VARS, PROC);

}

// Describe this function...
function vA1() {
  disable();
  tweenCamera('', 'A1', 0.5, function() {}, 0);
  registerSetTimeout(0.7, function() {
    tweenCamera('A1', 'pCube13', 3, function() {

      Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', 'mostrarBotonLibre();')(appInstance, v3d, PL, VARS, PROC);


      operateAnimation('PLAY', 'Armature.001', null, null, 'AUTO', 1,
              function() {}, false);

          }, 0);
  });
}

// Describe this function...
function vA2() {
  disable();
  tweenCamera('', 'Cartel1', 0.5, function() {}, 0);
  registerSetTimeout(1, function() {
    tweenCamera('A2', 'Cartel1', 2, function() {}, 0);
    outline('polySurface1105', 'ENABLE');
    outline('polySurface1078', 'ENABLE');
    outline('pCylinder11.001', 'ENABLE');
    outline('pCylinder11', 'ENABLE');
    outline('polySurface1080', 'ENABLE');
    outline('polySurface1081', 'ENABLE');

    operateAnimation('PLAY', 'Armature.001', null, null, 'AUTO', 1,
            function() {}, false);

        });
}

// Describe this function...
function vA3() {
  tweenCamera('', 'Cylinder2739', 0.5, function() {}, 0);
  registerSetTimeout(1, function() {
    tweenCamera('A3', 'pCylinder92', 3, function() {}, 0);
    outline('polySurface1171', 'ENABLE');
    outline('Shape069', 'ENABLE');
  });
}

// Describe this function...
function vA4() {
  disable();
  tweenCamera('', 'polySurface1107', 0.5, function() {}, 0);
  registerSetTimeout(1, function() {
    tweenCamera('A3', 'polySurface1107', 3, function() {
      outline('polySurface1107', 'ENABLE');
      zoomCamera('polySurface1107', 1, function() {});
    }, 0);
  });
}

// Describe this function...
function vA5() {
  disable();
  tweenCamera('', 'A5', 0.5, function() {}, 0);
  registerSetTimeout(1, function() {
    tweenCamera('A5', 'polySurface1145', 3, function() {}, 0);
    outline('Cylinder2750', 'ENABLE');
    outline('polySurface1145', 'ENABLE');
  });
}

// Describe this function...
function vA6() {
  disable();
  tweenCamera('', 'A6', 0.5, function() {}, 0);
  registerSetTimeout(1, function() {
    tweenCamera('A6', 'A6-1', 1, function() {
      tweenCamera('A6-1', 'A6-2', 1, function() {
        tweenCamera('A6-1', 'A6-2', 1, function() {
          tweenCamera('A6-2', 'A6-3', 1, function() {
            tweenCamera('A6-3', 'TanqueAC', 1, function() {
              outline('Cylinder2750', 'ENABLE');
              outline('polySurface1145', 'ENABLE');
            }, 0);
          }, 0);
        }, 0);
      }, 0);
    }, 0);
  });
}

// removeObject puzzles
function removeObject(objSelector) {
    var objNames = PzLib.retrieveObjectNames(objSelector);

    for (var i = 0; i < objNames.length; i++) {
        var objName = objNames[i]
        if (!objName)
            continue;
        var obj = PzLib.getObjectByName(objName);
        if (!obj || !obj.parent)
            continue;

        obj.parent.remove(obj);

        // clean object cache
        _pGlob.objCache = {};
    }
}

// Describe this function...
function vB1() {
  disable();
  registerSetTimeout(0.5, function() {
    tweenCamera('', 'A3', 0.5, function() {}, 0);
    registerSetTimeout(0.6, function() {
      tweenCamera('A3', 'pCube133.003', 0.5, function() {
        outline('pCube133.003', 'ENABLE');
        zoomCamera('pCube133.003', 0.5, function() {
          removeObject('Cone');
          removeObject('Body_Lores_GEO');

          operateAnimation('PLAY', 'Puerta1', 0, 101, 'LoopOnce', 0.7,
                  function() {}, false);


          operateAnimation('PLAY', 'Puerta2', 0, 101, 'LoopOnce', 0.7,
                  function() {}, false);

              });
      }, 0);
    });
  });
}

// Describe this function...
function vB2() {
  disable();
  tweenCamera('', 'B2', 0.5, function() {}, 0);
  registerSetTimeout(0.6, function() {
    tweenCamera('B2', 'pCube133', 0.5, function() {}, 0);
    outline('pCube133', 'ENABLE');
  });
}

// Describe this function...
function vB3() {
  disable();
  tweenCamera('', 'B3-4', 0.5, function() {}, 0);
  registerSetTimeout(0.6, function() {
    tweenCamera('B3-4', 'pCube133.001', 0.5, function() {
      zoomCamera('pCube133.001', 0.5, function() {});
    }, 0);
    outline('pCube133.001', 'ENABLE');
  });
}

// Describe this function...
function vB4() {
  disable();
  tweenCamera('', 'B3-4', 0.5, function() {}, 0);
  registerSetTimeout(0.6, function() {
    tweenCamera('B3-4', 'pCube133.007', 0.5, function() {
      zoomCamera('pCube133.007', 0.5, function() {});
    }, 0);
    outline('pCube133.007', 'ENABLE');
  });
}

// Describe this function...
function vB5() {
  disable();
  tweenCamera('', 'A5', 0.5, function() {}, 0);
  registerSetTimeout(0.6, function() {
    tweenCamera('A5', 'pCube133.005', 0.5, function() {
      zoomCamera('pCube133.005', 0.5, function() {});
    }, 0);
    outline('pCube133.005', 'ENABLE');
  });
}

// Describe this function...
function vB6() {
  disable();
  tweenCamera('', 'A6', 0.5, function() {}, 0);
  registerSetTimeout(1, function() {
    tweenCamera('A6', 'A6-1', 1, function() {
      tweenCamera('A6-1', 'A6-2', 1, function() {
        tweenCamera('A6-1', 'A6-2', 1, function() {
          tweenCamera('A6-2', 'A6-3', 1, function() {
            tweenCamera('A6-3', 'pCube133.006', 1, function() {
              outline('pCube133.006', 'ENABLE');
              zoomCamera('pCube133.006', 0.5, function() {});
            }, 0);
          }, 0);
        }, 0);
      }, 0);
    }, 0);
  });
}

// Describe this function...
function vB7() {
  Cambio();
  outline('pCube133.004', 'ENABLE');
  registerSetTimeout(0.5, function() {
    disable();
    tweenCamera('', 'B7', 0.5, function() {}, 0);
    registerSetTimeout(0.6, function() {
      outline('pCube133.004', 'ENABLE');
      tweenCamera('B7', 'pCube133.004', 0.5, function() {
        zoomCamera('pCube133.004', 0.5, function() {});
      }, 0);
    });
  });
}

// Describe this function...
function vB8() {
  Cambio();
  outline('pCube133.002', 'ENABLE');
  registerSetTimeout(0.5, function() {
    disable();
    tweenCamera('', 'pCube133.002', 0.5, function() {}, 0);
    registerSetTimeout(0.6, function() {
      outline('pCube133.002', 'ENABLE');
      tweenCamera('B8', 'pCube133.002', 0.5, function() {
        zoomCamera('pCube133.002', 0.5, function() {});
      }, 0);
    });
  });
}

// Describe this function...
function vBx() {
  disable();
  registerSetTimeout(0.2, function() {
    posGeneral();
    registerSetTimeout(1.2, function() {
      outline('pCube133.002', 'ENABLE');
      outline('pCube133.004', 'ENABLE');
      outline(VB6_obj, 'ENABLE');
      outline('pCube133.001', 'ENABLE');
      outline('pCube133.007', 'ENABLE');
      outline('pCube133', 'ENABLE');
      outline('pCube133.003', 'ENABLE');
      outline('pCube133.005', 'ENABLE');
      outline('pCube133.006', 'ENABLE');
    });
  });
}

// Describe this function...
function vC1() {
  quitarAlarmas();

  Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('crearOndas3d("Reunion1", {' + '\n' +
  '  radioInicial: 2,' + '\n' +
  '  radioFinal: 20,' + '\n' +
  '  duracion: 6,' + '\n' +
  '  numOndas: 4' + '\n' +
  '});' + '\n' +
  '')))(appInstance, v3d, PL, VARS, PROC);

  posGeneral();
  ModoP1();
  registerSetTimeout(1, function() {
    tweenCamera('C1', 'Reunion1', 1, function() {
      zoomCamera('Reunion1.001', 1, function() {
        handleAnnot(true, '1', 'Reunion1', '', 'R1', undefined);

        operateAnimation('PLAY', 'Armature.001', null, null, 'AUTO', 1,
                function() {}, false);


        operateAnimation('PLAY', 'Armature.002', null, null, 'AUTO', 1,
                function() {}, false);

            });
    }, 0);
  });
}

// Describe this function...
function vC2() {
  quitarAlarmas();

  Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('crearOndas3d("Reunion2", {' + '\n' +
  '  radioInicial: 2,' + '\n' +
  '  radioFinal: 20,' + '\n' +
  '  duracion: 6,' + '\n' +
  '  numOndas: 4' + '\n' +
  '});' + '\n' +
  '')))(appInstance, v3d, PL, VARS, PROC);

  posGeneral();
  handleAnnot(true, 'Espesadores', 'ZoneC', '', 'zoneC', undefined);
  registerSetTimeout(1, function() {
    ModoP1();
    tweenCamera('C2', 'Reunion2', 1, function() {
      zoomCamera('Reunion2.001', 1, function() {
        handleAnnot(true, '2', 'Reunion2', '', 'R2', undefined);
      });
    }, 0);
  });
}

// Describe this function...
function vC3() {
  quitarAlarmas();

  Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('crearOndas3d("Reunion3", {' + '\n' +
  '  radioInicial: 2,' + '\n' +
  '  radioFinal: 20,' + '\n' +
  '  duracion: 6,' + '\n' +
  '  numOndas: 4' + '\n' +
  '});' + '\n' +
  '')))(appInstance, v3d, PL, VARS, PROC);

  posGeneral();
  outline(['ALL_OBJECTS'], 'DISABLE');
  handleAnnot(true, 'Comedor', 'ZoneD', '', 'zoneC', undefined);
  registerSetTimeout(1, function() {
    ModoP1();
    tweenCamera('C3', 'Reunion3', 1, function() {
      zoomCamera('Reunion3.001', 1, function() {
        handleAnnot(true, '3', 'Reunion3', '', 'R3', undefined);
      });
    }, 0);
  });
}

// Describe this function...
function vC4() {
  quitarAlarmas();

  Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('crearOndas3d("Reunion4", {' + '\n' +
  '  radioInicial: 2,' + '\n' +
  '  radioFinal: 20,' + '\n' +
  '  duracion: 6,' + '\n' +
  '  numOndas: 4' + '\n' +
  '});' + '\n' +
  '')))(appInstance, v3d, PL, VARS, PROC);

  outline(['ALL_OBJECTS'], 'DISABLE');
  handleAnnot(true, 'Planta de Filtros y Despacho Cu', 'ZoneE', '', 'zoneC', undefined);
  posGeneral();
  registerSetTimeout(1, function() {
    ModoP1();
    tweenCamera('C4', 'Reunion4', 1, function() {
      zoomCamera('Reunion4.001', 1, function() {
        handleAnnot(true, '4', 'Reunion4', '', 'R4', undefined);
      });
    }, 0);
  });
}

// Describe this function...
function vCx() {
  quitarAlarmas();
  outline(['ALL_OBJECTS'], 'DISABLE');
  Cambio();
}

// Describe this function...
function vD1() {
  quitarAlarmas();

  Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('resaltarAlarma(' + '\n' +
  '    "polySurface1146",' + '\n' +
  '    "Rectangle3122.003",' + '\n' +
  '    "Mesh.6533_0",' + '\n' +
  '    "Mesh.6307_0",' + '\n' +
  '    "Mesh.6307_1_1",' + '\n' +
  '    "techo_mesh",' + '\n' +
  '    "techo_mesh1",' + '\n' +
  '    "polySurface1109",' + '\n' +
  '    "barandas_mesh_478",' + '\n' +
  '    "polySurface1074",' + '\n' +
  '    "estructura_mesh_1210",' + '\n' +
  '    "estructura_mesh_839"' + '\n' +
  ');')))(appInstance, v3d, PL, VARS, PROC);


  Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('crearCardModulo(' + '\n' +
  '  "Evacuación de la Planta de Molibdeno",' + '\n' +
  '  "../img/C.png",' + '\n' +
  '  { duration: 2500 }' + '\n' +
  ');')))(appInstance, v3d, PL, VARS, PROC);

  posGeneral();
  registerSetTimeout(0.2, function() {

    Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', 'audio("../media/a.mp4");')(appInstance, v3d, PL, VARS, PROC);


    Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', 'crearCaminoFlechas("ruta_D1",  ["D1-1",  "D1-2",  "D1-3"]);')(appInstance, v3d, PL, VARS, PROC);

    registerSetTimeout(0.2, function() {

      Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', 'crearCaminoFlechas("ruta_D2",  ["D2-1",  "D2-2",  "D2-3",  "D2-4"]);')(appInstance, v3d, PL, VARS, PROC);

    });
  });
}

// Describe this function...
function quitarAlarmas() {

  Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', 'detenerAlarma();')(appInstance, v3d, PL, VARS, PROC);


  Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('quitarAudios();' + '\n' +
  '')))(appInstance, v3d, PL, VARS, PROC);


  Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', 'eliminarCaminoFlechas();')(appInstance, v3d, PL, VARS, PROC);

}

// Describe this function...
function vD2() {
  quitarAlarmas();

  Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('resaltarAlarma(' + '\n' +
  '    "polySurface341.001",' + '\n' +
  '    "polySurface341",' + '\n' +
  '    "estructura_mesh_280",' + '\n' +
  '    "estructura_mesh_1007",' + '\n' +
  '    "extension_mesh_1086",' + '\n' +
  '    "extension_mesh_506",' + '\n' +
  '    ' + '\n' +
  '    "Mesh.6843_3_3",' + '\n' +
  '    "Mesh.6843_1_1",    ' + '\n' +
  '    ' + '\n' +
  '    "Mesh.6306_0",' + '\n' +
  '    "Mesh.3868_2_2",' + '\n' +
  '    "Mesh.3867_1_1",' + '\n' +
  '    "extension_mesh_2261",' + '\n' +
  '    "Mesh.7329_1_1",' + '\n' +
  '    "techo_mesh1"' + '\n' +
  ');')))(appInstance, v3d, PL, VARS, PROC);


  Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('crearCardModulo(' + '\n' +
  '  "Evacuación de la Planta de Molibdeno y áreas de influencia",' + '\n' +
  '  "../img/C.png",' + '\n' +
  '  { duration: 2500 }' + '\n' +
  ');')))(appInstance, v3d, PL, VARS, PROC);

  posGeneral();
  registerSetTimeout(0.2, function() {

    Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('resaltarAlarma(' + '\n' +
    '    "polySurface1146",' + '\n' +
    '    "Rectangle3122.003",' + '\n' +
    '    "Mesh.6533_0",' + '\n' +
    '    "Mesh.6307_0",' + '\n' +
    '    "Mesh.6307_1_1",' + '\n' +
    '    "techo_mesh",' + '\n' +
    '    "techo_mesh1",' + '\n' +
    '    "polySurface1109",' + '\n' +
    '    "barandas_mesh_478",' + '\n' +
    '    "polySurface1074",' + '\n' +
    '    "estructura_mesh_1210",' + '\n' +
    '    "estructura_mesh_839",' + '\n' +
    '    "techo_mesh1"' + '\n' +
    ');')))(appInstance, v3d, PL, VARS, PROC);


    Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', 'audio("../media/b.mp4");')(appInstance, v3d, PL, VARS, PROC);


    Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', 'crearCaminoFlechas("ruta_D3A", ["D3A-1", "D3A-2"]);')(appInstance, v3d, PL, VARS, PROC);

    registerSetTimeout(0.2, function() {

      Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', 'crearCaminoFlechas("ruta_D3B", ["D3B-1", "D3B-2", "D3B-3", "D3B-4","D3A-2"]);')(appInstance, v3d, PL, VARS, PROC);

      registerSetTimeout(0.2, function() {

        Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', 'crearCaminoFlechas("ruta_D4",  ["D4-1",  "D4-2",  "D4-3",  "D4-4"]);')(appInstance, v3d, PL, VARS, PROC);

        registerSetTimeout(0.2, function() {

          Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', 'crearCaminoFlechas("ruta_D1",  ["D1-1",  "D1-2",  "D1-3"]);')(appInstance, v3d, PL, VARS, PROC);

          registerSetTimeout(0.2, function() {

            Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', 'crearCaminoFlechas("ruta_D2",  ["D2-1",  "D2-2",  "D2-3",  "D2-4"]);')(appInstance, v3d, PL, VARS, PROC);

          });
        });
      });
    });
  });
}


  zoomCamera('general', 0.5, function() {});
  hideObj = ['Rectangle3122.003', null, null];
  changeVis(hideObj, false);

  operateAnimation('STOP', 'Armature', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('STOP', 'Puerta1', null, null, 'AUTO', 1,
          function() {}, false);


  operateAnimation('STOP', 'Puerta2', null, null, 'AUTO', 1,
          function() {}, false);


  Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('window.app = app; ' + '\n' +
  'import("./imports.js");' + '\n' +
  '')))(appInstance, v3d, PL, VARS, PROC);

  posGeneral();

  Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', 'app.controls.enableRotate = false;')(appInstance, v3d, PL, VARS, PROC);

  setCameraParam('KEYBOARD_CONTROLS', 'Camera', false);
  setCameraParam('ALLOW_PANNING', 'Camera', false);
  registerSetTimeout(1.1, function() {
    zoomCamera('general', 0.5, function() {
      changeVis('general', false);
    });
  });
  registerSetTimeout(1.1, function() {
    zoomCamera('general', 0.5, function() {});
  });

  changeVis('Cone', false);
  changeVis('Body_Lores_GEO', false);



} // end of PL.init function

PL.disposeListeners = function() {
    if (_pGlob) {
        _pGlob.eventListeners.forEach(({ target, type, listener, optionsOrUseCapture }) => {
            target.removeEventListener(type, listener, optionsOrUseCapture);
        });
        _pGlob.eventListeners.length = 0;
    }
}

PL.disposeHTMLElements = function() {
    if (_pGlob) {
        _pGlob.htmlElements.forEach(elem => {
            elem.remove();
        });
        _pGlob.htmlElements.clear();
    }
}

PL.disposeMaterialsCache = function() {
    if (_pGlob) {
        for (const mat of _pGlob.materialsCache.values()) {
            mat.dispose();
        }
        _pGlob.materialsCache.clear();
    }
}

PL.dispose = function() {
    PL.disposeListeners();
    PL.disposeHTMLElements();
    PL.disposeMaterialsCache();
    _pGlob = null;
    // backward compatibility
    if (v3d[Symbol.toStringTag] !== 'Module') {
        delete v3d.PL;
        delete v3d.puzzles;
    }
}



return PL;

}

export { createPL };
